name: Build and deploy hugo site

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  build:
    name: Build and deploy hugo site
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:exts
      volumes: 
        - ./src:/src
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          submodules: recursive
      - name: Run commands
        run: |
          hugo -s ./src
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './src/public'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
